### ISSUE TITLE
how to calculate number of samples in one full pass of BatchIterator

### ISSUE THREAD

**Issue by kaczmarj** [DIAGNijmegen/pathology-whole-slide-data#10]
Hi, thank you for creating this excellent tool. I am using the BatchIterator as in [the example notebook](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/main/notebooks/04%20-%20BatchIterator.ipynb), and I would like to understand how to calculate the number of samples in a single pass through the batch iterator.

I would like to know this for a deep learning application. I am hoping to use this tool to extract tissues and their corresponding annotations and save those to disk. However, I need to know how many samples are present in my dataset.

**Comment by martvanrijthoven** [comment]
Dear Jakub Kaczmarzyk,

Thank you for your interest and your kind words about this package!

The number of samples in the batch iterator depends on your defined settings. 
First of all, there is an 'infinite' and 'finite' mode for the batch iterator determined by the **number_of_batches** argument.

**Infinite batch iterator**
If you don't give number_of_batches as an argument or set it to 'None,' the batch iterator will never reset itself. Suppose you, for example, use a RandomPointSampler. In that case, there is no way to know how many different patches/masks the batch iterator _will_ sample before you stop the iterator. Though, the maximum number of different patches it _can_ sample (if you let it run for a long time) is equal to the total area of all annotations combined in your dataset. Please note that some patches are then only shifted by one pixel.

**Finite batch iterator**
if you give a value to number_of_batches, this value*batch_size will be the number of samples in your dataset. After sampling number_of_batches. The batch iterator will reset itself and will sample the same patches again.

You can also give the number_of_batches a value of '-1'. Then the batch iterator will sample as many available samples as annotations. You might want to consider using AnnotationCountedLabelSampler and the OrderedAnnotationSampler to make sure that you also sample from all available annotations. If you would use a RandomLabelSampler, you might not get all the annotations because one sample could be sampled two times due to the randomness.
To get the number of samples you can call:

`len(batch_iterator)*batch_iterator.batch_size-batch_iterator._redundant.`

Furthermore, you can also print  `batch_iterator.dataset.annotations_per_label_per_key` to see info about the available annotations.

I want to note that I would not recommend saving the output to disk. This package is developed to be used for online sampling (i.e., while training). Online sampling allows you to test different input sizes, different sampling strategies, and different data augmentations without the need to create separate datasets and without the need to save all the output to disk for each different setting. But, of course, if you want to, you can use this package to save the output to disk :wink:
