### ISSUE TITLE
Sliding Window configuration

### ISSUE THREAD

**Issue by michelbotros** [DIAGNijmegen/pathology-whole-slide-data#30]
Hi Mart,

I am working with the Sliding Window configuration as shown in: https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/main/notebooks/tiger/sliding_window/slidingwindowconfig.yml

Is it possible to use a sliding window configuration without the ASAP backend? I can’t install ASAP or use Docker on the server that I am working on currently (working on getting this fixed). But in the meantime I am looking for a workaround. 

Let me know whether this is possible.

Thank you,

Michel

**Comment by martvanrijthoven** [comment]
Dear Michel,

It might be a bit confusing, but there are two types of a 'sliding window'

The first one is based on a tissue mask. That type needs a [configuration](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/main/notebooks/tiger/sliding_window/slidingwindowconfig.yml) you mentioned: 
This is mainly for looping over a tissue mask such that a model only needs to predict patches where there is tissue. This requires ASAP, because openslide has trouble reading monochrome images. Pyvips might work but I have not implemented this yet.

The second one is a sliding window loop over the annotations in a dataset, such that all annotated regions are retrieved systematically. This does not depend on any backend. You can find a [notebook](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/main/notebooks/SlidingWindowSampling.ipynb)  and [config](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/main/notebooks/configs/slidingwindowsampling.yml) in the notebooks folder.

Please let me know if you have any questions about it.

Best wishes,
Mart

**Comment by michelbotros** [comment]
@martvanrijthoven I needed the second option and its working perfectly.

Thank you for the example!

**Comment by martvanrijthoven** [comment]
Dear Michel,

Great to hear that it works for you!

Best wishes,
Mart

**Comment by martvanrijthoven** [comment]
Hi Michel, 

You can change the tile size: https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/799683950e406ce701f1cf8d510ee4e834039a9c/notebooks/configs/slidingwindowsampling.yml#L24

In that example, the input size is 256. If you set the tile_size to 128 instead of 256, you should get a 50% overlap.

Best wishes,
Mart

**Comment by michelbotros** [comment]
Thanks Mart, it went over my head that it takes into account the ratio between the batch shape spacing and spacing level 0 in the image as well.
